### ISSUE TITLE
This Serverless Function has timed out. 请帮忙处理谢谢

### ISSUE THREAD

**Issue by sdlkhfksl** [zhile-io/pandora-cloud-serverless#12]
This Serverless Function has timed out.

Your connection is working correctly.

Vercel is working correctly.

504: GATEWAY_TIMEOUT
Code: FUNCTION_INVOCATION_TIMEOUT
ID: sfo1::hws94-1698478618032-caaad4c0bd05

**Comment by vicar5235** [comment]
我也遇到了，好多天了，期待修复

**Comment by randolph555** [comment]
+1

**Comment by sdlkhfksl** [comment]
好了
